/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/pose-analysis/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pose Analysis Job */
        get: operations["get_pose_analysis_job_api_ai_pose_analysis_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/records/{record_id}/pose-analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pose Analysis */
        get: operations["get_pose_analysis_api_ai_records__record_id__pose_analysis_get"];
        put?: never;
        /**
         * Trigger Pose Analysis
         * @description 同步执行姿态分析，并返回分析结果。
         */
        post: operations["trigger_pose_analysis_api_ai_records__record_id__pose_analysis_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/records/{record_id}/pose-analysis/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Pose Analysis Job
         * @description 创建姿态分析异步任务（推荐方式）。
         */
        post: operations["create_pose_analysis_job_api_ai_records__record_id__pose_analysis_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/records/{record_id}/pose-analysis/jobs/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Latest Pose Analysis Job
         * @description Return the latest job for the current video revision so clients can reconnect.
         */
        get: operations["get_latest_pose_analysis_job_api_ai_records__record_id__pose_analysis_jobs_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/records/{record_id}/pose-scoring": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Score Pose Analysis */
        post: operations["score_pose_analysis_api_ai_records__record_id__pose_scoring_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description 用户登录
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Token
         * @description 刷新访问令牌。
         *
         *     使用有效的 refresh_token 换取新的 access_token + refresh_token（轮换）。
         */
        post: operations["refresh_token_api_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description 用户注册
         */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercise/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Exercises
         * @description 获取标准动作列表
         */
        get: operations["get_exercises_api_exercise_exercises_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercise/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Records
         * @description 获取用户运动记录（支持日期范围、动作 ID 过滤）。
         */
        get: operations["get_user_records_api_exercise_records_get"];
        put?: never;
        /**
         * Create Record
         * @description 创建运动记录
         */
        post: operations["create_record_api_exercise_records_post"];
        /**
         * Batch Delete Records
         * @description 批量删除运动记录
         */
        delete: operations["batch_delete_records_api_exercise_records_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercise/records/page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Records Page
         * @description 获取用户运动记录分页响应（含总数和分页元数据）。
         */
        get: operations["get_user_records_page_api_exercise_records_page_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercise/records/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Record Detail
         * @description 获取单条运动记录详情
         */
        get: operations["get_record_detail_api_exercise_records__record_id__get"];
        /**
         * Update Record
         * @description 修改运动记录
         */
        put: operations["update_record_api_exercise_records__record_id__put"];
        post?: never;
        /**
         * Delete Record
         * @description 删除运动记录
         */
        delete: operations["delete_record_api_exercise_records__record_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/personal-best": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Personal Best
         * @description 获取各动作个人最好成绩
         */
        get: operations["get_personal_best_api_stats_personal_best_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stats Summary
         * @description 获取用户综合运动统计
         */
        get: operations["get_stats_summary_api_stats_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/weekly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Weekly Stats
         * @description 获取最近 7 天每日运动统计
         */
        get: operations["get_weekly_stats_api_stats_weekly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Account
         * @description 注销当前账户（硬删除）
         */
        delete: operations["delete_account_api_user_account_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Change Password
         * @description 修改当前用户密码
         */
        put: operations["change_password_api_user_password_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Profile
         * @description 获取当前用户资料
         */
        get: operations["get_profile_api_user_profile_get"];
        /**
         * Update Profile
         * @description 更新当前用户资料
         */
        put: operations["update_profile_api_user_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/video/records/{record_id}/video": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Video
         * @description 上传运动记录视频
         */
        post: operations["upload_video_api_video_records__record_id__video_post"];
        /**
         * Delete Video
         * @description 删除运动记录关联视频
         */
        delete: operations["delete_video_api_video_records__record_id__video_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/video/videos/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Video
         * @description 获取已上传的视频文件（需认证 + 归属校验）
         */
        get: operations["get_video_api_video_videos__filename__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountDelete */
        AccountDelete: {
            /** Password */
            password: string;
        };
        /** Body_login_api_auth_login_post */
        Body_login_api_auth_login_post: {
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
            /** Grant Type */
            grant_type?: string | null;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Username */
            username: string;
        };
        /** Body_upload_video_api_video_records__record_id__video_post */
        Body_upload_video_api_video_records__record_id__video_post: {
            /**
             * Video
             * Format: binary
             */
            video: string;
        };
        /** CategoryStats */
        CategoryStats: {
            /** Average Score */
            average_score: number;
            /** Category */
            category: string;
            /** Count */
            count: number;
        };
        /** ExerciseRecordCreate */
        ExerciseRecordCreate: {
            /**
             * Count
             * @description 完成次数
             */
            count: number;
            /**
             * Duration
             * @description 时长 (秒)
             */
            duration: number;
            /** Exercise Id */
            exercise_id: number;
            /** Heart Rate Avg */
            heart_rate_avg?: number | null;
            /** Heart Rate Max */
            heart_rate_max?: number | null;
            /**
             * Score
             * @description 动作评分 0-100
             */
            score: number;
        };
        /**
         * ExerciseRecordPage
         * @description 分页运动记录响应。
         */
        ExerciseRecordPage: {
            /** Items */
            items: components["schemas"]["ExerciseRecordResponse"][];
            /** Limit */
            limit: number;
            /** Skip */
            skip: number;
            /** Total */
            total: number;
        };
        /** ExerciseRecordResponse */
        ExerciseRecordResponse: {
            /** Analysis Model */
            analysis_model: string | null;
            /** Analysis Revision */
            analysis_revision: number | null;
            /** Analysis Rule Version */
            analysis_rule_version: string | null;
            /** Count */
            count: number;
            /** Count Source */
            count_source: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration */
            duration: number;
            /** Exercise Id */
            exercise_id: number;
            /** Feedback */
            feedback: string | null;
            /** Heart Rate Avg */
            heart_rate_avg: number | null;
            /** Id */
            id: number;
            /** Manual Count */
            manual_count: number | null;
            /** Manual Score */
            manual_score: number | null;
            /** Score */
            score: number;
            /** Score Source */
            score_source: string;
            /** Video Revision */
            video_revision: number;
            /** Video Url */
            video_url: string | null;
        };
        /** ExerciseRecordUpdate */
        ExerciseRecordUpdate: {
            /**
             * Count
             * @description 完成次数
             */
            count?: number | null;
            /**
             * Duration
             * @description 时长 (秒)
             */
            duration?: number | null;
            /** Heart Rate Avg */
            heart_rate_avg?: number | null;
            /** Heart Rate Max */
            heart_rate_max?: number | null;
            /**
             * Score
             * @description 动作评分 0-100
             */
            score?: number | null;
        };
        /** ExerciseResponse */
        ExerciseResponse: {
            /** Aliases */
            aliases?: string[];
            /** Analysis Rule Version */
            analysis_rule_version?: string | null;
            /** Analysis Status Reason */
            analysis_status_reason?: string | null;
            /**
             * Analysis Supported
             * @default false
             */
            analysis_supported: boolean;
            /** Body Part */
            body_part?: string | null;
            /** Campus Candidate Reason */
            campus_candidate_reason?: string | null;
            /** Canonical Action Key */
            canonical_action_key?: string | null;
            /** Category */
            category: string | null;
            /** Description */
            description: string | null;
            /** Equipment */
            equipment?: string | null;
            /** External Id */
            external_id?: string | null;
            /** Id */
            id: number;
            /** Instruction Steps */
            instruction_steps?: {
                [key: string]: unknown;
            };
            /** Instructions */
            instructions?: {
                [key: string]: unknown;
            };
            /**
             * Is Bodyweight
             * @default false
             */
            is_bodyweight: boolean;
            /**
             * Is Low Equipment Candidate
             * @default false
             */
            is_low_equipment_candidate: boolean;
            /** Media Attribution */
            media_attribution?: string | null;
            /** Muscle Group */
            muscle_group?: string | null;
            /** Name */
            name: string;
            /** Secondary Muscles */
            secondary_muscles?: string[];
            /** Source */
            source?: string | null;
            /** Target */
            target?: string | null;
            /** Target Muscles */
            target_muscles?: string[];
        };
        /** ExerciseStats */
        ExerciseStats: {
            /** Average Score */
            average_score: number;
            /** Best Score */
            best_score: number;
            /** Total Duration */
            total_duration: number;
            /** Total Repetitions */
            total_repetitions: number;
            /** Total Sessions */
            total_sessions: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PasswordChange */
        PasswordChange: {
            /** New Password */
            new_password: string;
            /** Old Password */
            old_password: string;
        };
        /** PoseAnalysisFrame */
        PoseAnalysisFrame: {
            /** Coordinate Space */
            coordinate_space?: string | null;
            /** Frame */
            frame?: {
                [key: string]: unknown;
            } | null;
            /** Frame Index */
            frame_index: number;
            /** Keypoints */
            keypoints: {
                [key: string]: unknown;
            }[];
            /** Timestamp Ms */
            timestamp_ms: number;
        };
        /** PoseAnalysisJobResponse */
        PoseAnalysisJobResponse: {
            /** Completed At */
            completed_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error?: string | null;
            /** Id */
            id: number;
            /** Record Id */
            record_id: number;
            /** Result Summary */
            result_summary?: {
                [key: string]: unknown;
            } | null;
            /** Sample Fps */
            sample_fps?: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed" | "cancelled";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Video Revision */
            video_revision: number;
        };
        /** PoseAnalysisModelMetadata */
        PoseAnalysisModelMetadata: {
            /** Backend */
            backend?: string | null;
            /** Input Size */
            input_size?: number | null;
            /** Name */
            name?: string | null;
        };
        /** PoseAnalysisResponse */
        PoseAnalysisResponse: {
            /** Analysis Revision */
            analysis_revision?: number | null;
            /** Error */
            error?: string | null;
            /**
             * Frames
             * @default []
             */
            frames: components["schemas"]["PoseAnalysisFrame"][];
            model?: components["schemas"]["PoseAnalysisModelMetadata"] | null;
            /** Record Id */
            record_id: number;
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /**
             * Status
             * @enum {string}
             */
            status: "idle" | "done" | "failed";
            summary?: components["schemas"]["PoseAnalysisSummary"] | null;
            /**
             * Video Revision
             * @default 0
             */
            video_revision: number;
        };
        /** PoseAnalysisSummary */
        PoseAnalysisSummary: {
            /**
             * Average Confidence
             * @default 0
             */
            average_confidence: number;
            /**
             * Processed Frames
             * @default 0
             */
            processed_frames: number;
            /** Sample Fps */
            sample_fps: number;
            /**
             * Sampled Frames
             * @default 0
             */
            sampled_frames: number;
            /** Source Fps */
            source_fps?: number | null;
            /**
             * Total Frames
             * @default 0
             */
            total_frames: number;
            /**
             * Valid Frame Count
             * @default 0
             */
            valid_frame_count: number;
        };
        /** PoseAnalysisTriggerRequest */
        PoseAnalysisTriggerRequest: {
            /** Sample Fps */
            sample_fps?: number | null;
        };
        /** PoseScoringRequest */
        PoseScoringRequest: {
            /**
             * Apply
             * @default false
             */
            apply: boolean;
        };
        /** PoseScoringResponse */
        PoseScoringResponse: {
            /**
             * Applied
             * @default false
             */
            applied: boolean;
            /** Auto Count */
            auto_count?: number | null;
            /** Confidence */
            confidence?: number | null;
            /** Count */
            count?: number | null;
            /** Count Source */
            count_source?: string | null;
            /** Exercise Type */
            exercise_type?: string | null;
            /** Feedback */
            feedback?: string[];
            /** Metrics */
            metrics?: {
                [key: string]: unknown;
            };
            /** Record Id */
            record_id: number;
            /** Rule Version */
            rule_version?: string | null;
            /** Score */
            score?: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "scored" | "unsupported";
        };
        /** RecentRecord */
        RecentRecord: {
            /** Count */
            count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Exercise Name */
            exercise_name: string;
            /** Id */
            id: number;
            /** Score */
            score: number;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** StatsSummary */
        StatsSummary: {
            /** Category Stats */
            category_stats: components["schemas"]["CategoryStats"][];
            exercise_stats: components["schemas"]["ExerciseStats"];
            /** Recent Records */
            recent_records: components["schemas"]["RecentRecord"][];
        };
        /** TokenWithRefresh */
        TokenWithRefresh: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /** Token Type */
            token_type: string;
        };
        /** UserCreate */
        UserCreate: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** UserProfileUpdate */
        UserProfileUpdate: {
            /** Email */
            email?: string | null;
            /** Username */
            username?: string | null;
        };
        /** UserResponse */
        UserResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Username */
            username: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_pose_analysis_job_api_ai_pose_analysis_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoseAnalysisJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pose_analysis_api_ai_records__record_id__pose_analysis_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoseAnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_pose_analysis_api_ai_records__record_id__pose_analysis_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PoseAnalysisTriggerRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoseAnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_pose_analysis_job_api_ai_records__record_id__pose_analysis_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PoseAnalysisTriggerRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoseAnalysisJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_pose_analysis_job_api_ai_records__record_id__pose_analysis_jobs_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoseAnalysisJobResponse"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    score_pose_analysis_api_ai_records__record_id__pose_scoring_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PoseScoringRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoseScoringResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenWithRefresh"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_token_api_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenWithRefresh"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exercises_api_exercise_exercises_get: {
        parameters: {
            query?: {
                /** @description 按名称、别名、部位、器械或肌群搜索 */
                q?: string | null;
                /** @description 按外部动作目录 equipment 过滤 */
                equipment?: string | null;
                /** @description 按外部动作目录 body_part 过滤 */
                body_part?: string | null;
                /** @description 仅返回已接入 AI 评分规则的动作 */
                analysis_supported?: boolean | null;
                /** @description 仅返回校园低器械候选动作 */
                campus_candidate?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_records_api_exercise_records_get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
                exercise_id?: number | null;
                /** @description 跳过的记录数 */
                skip?: number;
                /** @description 返回的记录数，范围 1-100 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseRecordResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_record_api_exercise_records_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseRecordCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseRecordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_delete_records_api_exercise_records_delete: {
        parameters: {
            query: {
                /** @description 要删除的记录 ID 列表 */
                record_ids: number[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_records_page_api_exercise_records_page_get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
                exercise_id?: number | null;
                /** @description 跳过的记录数 */
                skip?: number;
                /** @description 返回的记录数，范围 1-100 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseRecordPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_record_detail_api_exercise_records__record_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseRecordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_record_api_exercise_records__record_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseRecordUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseRecordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_record_api_exercise_records__record_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_personal_best_api_stats_personal_best_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_stats_summary_api_stats_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsSummary"];
                };
            };
        };
    };
    get_weekly_stats_api_stats_weekly_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    delete_account_api_user_account_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountDelete"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_password_api_user_password_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_user_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    update_profile_api_user_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_video_api_video_records__record_id__video_post: {
        parameters: {
            query?: {
                keep_video?: boolean;
            };
            header?: never;
            path: {
                record_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_video_api_video_records__record_id__video_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_video_api_video_records__record_id__video_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_video_api_video_videos__filename__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
